### PR TITLE
change polymorphic types to type constructors

### PR DESCRIPTION
**Pull request by capfredf**
this fix ensured the code to be forward compatible with
the upcoming TR's [kind system](https://github.com/racket/typed-racket/pull/1143)

### CODE REVIEW

**Comment by SuzanneSoy** [comment]
Hi, thanks for the patch!

IIUC, only the define-type in the tests needed to be updated? There's a lot of noise in the diff due to a whitespace change, just checking that I didn't miss anything :)

Kinds are exciting! Thanks for having worked on those for TR :)

**Comment by capfredf** [comment]
Sorry about the noise. I thought white space changes could be easily ignored via ([?w=1](https://github.com/SuzanneSoy/type-expander/pull/13/files?w=1) or `git diff -w`). I'll revert those white space changes. 

I used `raco test -p type-expander` to test the changed `type-expander` against the working TR branch and all tests passed. 

Do you have anything particular in mind that I need to test?

**Comment by SuzanneSoy** [comment]
Oooh, I never knew about ?w=1, that's a great trick! No need to revert the changes, don't worry.

I think `raco test -p type-expander` should be enough, I used to have a CI script but it suspect it won't work anymore since Travis changed things on their platform; I'll disable the checks and merge in a couple of hours.

**Comment by SuzanneSoy** [comment]
Sorry about the delay, merged. Thanks a lot for the fix :) !

**Pull request merged**
